name: All
on:
  workflow-dispatch

  workflow_call:
    inputs:
      name:
        required: true
        type: string
jobs:
  runs-on: ubuntu-latest
  job1:
    uses: hashicorp/setup-terraform@v3
    uses: actions/checkout@v4
    working-directory: Terraform/
    run: |
      terraform fmt -check
      terraform init
      terraform plan -no-color
      terraform apply -no-color -auto-approve
    shell: python
    run: |
        print("hi")