name: 0_basic

on:
  workflow_dispatch:  # Manual Trigger 
    inputs:
      name:
        required: true
        type: string
        
  workflow_call:      # Function
    inputs:
      name:
        required: true
        type: string

env:
  TF_VAR_token: ${{ secrets.KEY }}  # TF_VAR prefix mandatory for Terraform
  
jobs:
  job1:  
    runs-on: ubuntu-latest     
    if: false #Disable
    steps:         
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Terraform Commands
        run: |
          cd Terraform  # Change directory to Terraform
          terraform fmt -check
          terraform init
          terraform plan -no-color
          terraform apply -no-color -auto-approve

  job2:  
    runs-on: ubuntu-latest         
    steps:            
      - name: Print bash
        run: |
         echo ${{ inputs.name }}
         echo $TF_VAR_token
        
      - name: Run Python
        shell: python
        run: |
          import os
          os.getenv('name')
          os.getenv('TF_VAR_token')
          
