
#----------------------CALL REUSEABLE FUNCTION --------------------
# # URL =  https://github.com/j-thepac/gitactions/blob/main/.github/workflows/reusablefunctions.yml
# name: CallReusableFn
# on: [workflow_dispatch]
# jobs:                   
#   calljob:
#     uses: j-thepac/gitactions/.github/workflows/reusablefunctions.yml@main
#     with:
#       test_name: "test"
#     secrets:
#       password: "123"
# ---------------------------------------------------------------------


name: 4_1_Reusable_Function

on:
  workflow_call:
    inputs:
      test_name:
        required: true
        type: string
    secrets:
      password:
        required: true

jobs:
  fn:
    runs-on: ubuntu-latest 
    steps:
      - name: Print
        run: |
          echo ""${{ inputs.test_name }}
  
