#To trigger this JOb using an API  

name: 5_restapi
on:
  repository_dispatch:
    types: [startme]
   
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
        - run: echo  ${{ github.event.client_payload.message }}


# --------Python ---
# url = "https://api.github.com/repos/j-thepac/gitactions/dispatches"
# payload = json.dumps({
#   "event_type": "startme",
#   "client_payload": {
#     "message": "Some Message"
#   }
# })
# headers = {
#   'Accept': 'application/vnd.github+json',
#   'Content': 'application/json',
#   'Authorization': 'Bearer generate_personal_token',
#   'Content-Type': 'application/json'
# }
# response = requests.request("POST", url, headers=headers, data = payload)
#-----------

# curl --location --request POST 'https://api.github.com/repos/j-thepac/gitactions/dispatches' \
# --header 'Accept: application/vnd.github+json' \
# --header 'Content: application/json' \
# --header 'Authorization: Bearer <token>' \
# --header 'Content-Type: application/json' \
# --data-raw '{
#   "event_type": "startme",
#   "client_payload": {
#     "message": "Some Message"
#   }
# }'


