
name: 5_restapi
on:
  repository_dispatch:
    types: [startme]
   
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: python
        run: |
          from datetime import datetime
          print(datetime.now())

# --------Python ---
# url = "https://api.github.com/repos/j-thepac/gitactions/dispatches"
# payload = "{\n    \"event_type\": \"startme\"\n}"
# headers = {
#   'Accept': 'application/vnd.github+json',
#   'Content': 'application/json',
#   'Authorization': 'Bearer generate_personal_token',
#   'Content-Type': 'application/json'
# }
# response = requests.request("POST", url, headers=headers, data = payload)
#-----------

#------curl------
#   curl --location --request POST 'https://api.github.com/repos/j-thepac/gitactions/dispatches' \
#   --header 'Accept: application/vnd.github+json' \
#   --header 'Content: application/json' \
#   --header 'Authorization: Bearer generate_personal_token' \
#   --header 'Content-Type: application/json' \
#   --data-raw '{
#       "event_type": "startme"
#   }'


