# 1. place it under root/.github/workflows/
# 2. Workflow > Jobs[VM (runs-on)] > Actions > Steps
# 3. Events(on) Trigger Worflows
# "_" instead of "-"

name: Test
on: [workflow_dispatch]
#[push]

jobs:
  myjobname:
    runs-on: ubuntu-latest
    steps:
      - name: echo name
        shell: bash
        run: echo "hi"
        
      - name: multi
        shell: bash
        run: |
          node -v
          npm -v
          
      - name: call function gitcheckout_action
        uses: actions/checkout@v1
        
      - name: checkfiles
        shell: bash
        # git clone git_url  - can be added as well
        run: |
          ls
