# 1. place it under root/.github/workflows/
# 2. Workflow > Jobs[VM (runs-on)] > Actions > Steps
# 3. Events(on) Trigger Worflows
# "_" instead of "-"

name: basic
on: [workflow_dispatch]
#[push]

jobs:
  basicjob1:
    runs-on: ubuntu-latest
    steps:
#-------------- Basic ---------------    
      - name: echo name
        shell: bash
        run: echo "hi"
        
      - name: multiLine
        shell: bash
        run: |
          node -v
          npm -v
          
#------ git clone git_url  - can be added as well-------
      - name: call function gitcheckout_action
        uses: actions/checkout@v1
      
      - name: checkout files verify 
        shell: bash
        run: |
          ls
 #--------------Exteranl Function with Args --------------- 
      - name: simple function with Args
        id: id1
        uses: actions/hello-world-javascript-action@v1
        with:
          # INPUT
          who-to-greet: deepak
        
      - name: print output of Pervious Step
        run: echo "${{steps.id1.outputs.time}}"
