
name: docker
on: [workflow_dispatch]
jobs:
  myjobname:
    runs-on: ubuntu-latest
    container:
      image: broadinstitute/scala-baseimage:latest
    steps:
      - name: scalatest
        shell: bash
      - uses: actions/checkout:v1
        run: |
          scala
          'print("hi")'
            
