
name: docker
on: [workflow_dispatch]
jobs:
  myjobname:
    runs-on: ubuntu-latest
    container:
      image: broadinstitute/scala-baseimage:latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      
      - name: seeFolders
        shell: bash
        run: ls -la
        
      - name: scalatest
        shell: bash
        run: scala /.github/workflows//test.scala
            
