name: functions
on: [workflow_dispatch]
jobs:
  myjobname:
    runs-on: ubuntu-latest
    steps:
      - name: echo name
        shell: bash
        run: |
          echo ${{ contains( 'hello' ,'o')}}
          echo ${{ startsWith( 'hello' ,'o')}}
          echo ${{ endsWith( 'hello' ,'o')}}
          echo ${{ format('Hello {0} {1}' ,'A','B')}}
          
 
