name: gitcheckout
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: gitcheckout1
        uses: actions/checkout@v1
        shell: bash
        run: |
          ls
