name: gitcheckout
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: gitcheckout_action
        uses: actions/checkout@v1
        
      - name: checkfiles
        shell: bash
        # git clone git_url  - can be added as well
        run: |
          ls
