#https://docs.github.com/en/actions/learn-github-actions/expressions
name: functions
on: [workflow_dispatch]
jobs:
  myjobname:
    runs-on: ubuntu-latest
    steps:
      - name: echo name
        shell: bash
        # git hub string operations
        run: |
          echo ${{ contains( 'hello' ,'o')}}
          echo ${{ startsWith( 'hello' ,'o')}}
          echo ${{ endsWith( 'hello' ,'o')}}
          echo ${{ format('Hello {0} {1}' ,'A','B')}}
          echo ${{ join( '["csharp", "javascript"]', ',' )}}
          
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
        
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
        
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
        
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
        
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
        
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
          
 
