name: restprintpayload
on:
  repository_dispatch:
    types: [startme]
   
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: printPayload
        shell: bash
        run: echo ${{github.event.client_payload.name}}



#-----Python ----
# import requests
# url = "https://api.github.com/repos/j-thepac/gitactions/dispatches"
# payload = "{\n    \"event_type\": \"startme\",\n\"client_payload\":{\"name\":\"Mona the Octocat\",\"home\":\"San Francisco, CA\"}\n}"
# headers = {
#   'Accept': 'application/vnd.github+json',
#   'Content': 'application/json',
#   'Authorization': 'Bearer personel_token',
#   'Content-Type': 'application/json'
# }
# response = requests.request("POST", url, headers=headers, data = payload)

#--------curl
# curl --location --request POST 'https://api.github.com/repos/j-thepac/gitactions/dispatches' \
# --header 'Accept: application/vnd.github+json' \
# --header 'Content: application/json' \
# --header 'Authorization: Bearer personel_token' \
# --header 'Content-Type: application/json' \
# --data-raw '{
#     "event_type": "startme",
# "client_payload":{"name":"Mona the Octocat","home":"San Francisco, CA"}
# }'
