

name: rest
on:
  repository_dispatch:
    types: [startme]
   
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: python
        run: |
          from datetime import datetime
          print(datetime.now())
