

name: secrettest
on: [workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
   
    steps:
      - name: secret test
        shell: bash
        run: |
          echo "${secrets.KEY}"
          
 
     
