name: Test
on: 
    workflow_dispatch:
        inputs:
            a: 
              type: string

env:
  token: ${{ secrets.gitToken }}

jobs:
    job1:
       runs-on: [ubuntu-latest]
       steps:
          - name: A
            shell: bash
            run: |
             echo ${{inputs.a}}

            shell: python
            run: |
              import os
              print(len(os.system("token")))
             
