name: Test
on: 
    workflow_call:
        inputs:
            a: 
              type: string
jobs:
    job1:
       runs-on: [ubuntu-latest]
       steps:
          - name: A
            shell: bash
            run: |
             echo ${{a}}
